project_id = "nxcvnyssknbafcjyowrh"

[functions.process-receipt]
verify_jwt = false

[functions.google-drive-upload]
verify_jwt = false

[functions.google-sheets-sync]
verify_jwt = false

[functions.setup-google-storage]
verify_jwt = false

[functions.create-upload-session]
verify_jwt = true

[functions.phone-upload]
verify_jwt = false
